apiVersion: v1
appVersion: "1.1"
description: Trickster is an HTTP Reverse Proxy Cache and time series query accelerator.
name: trickster
version: 1.5.2
home: https://github.com/tricksterproxy/trickster
icon: https://helm.tricksterproxy.io/img/trickster-horizontal.png
sources:
  - https://github.com/tricksterproxy/trickster
engine: gotpl
tillerVersion: ">=2.8.0"
maintainers:
  - name: jranson
  - name: LimitlessEarth
  - name: crandles
